package ui.theme

val sign_in = "Sign in"
val splash_screen = "splashScreen"
val sign_in_screen = "signInScreen"
val dashboard_screen = "dashboardScreen"
val username_string = "Username"
val password_string = "Password"
val support_key = "Support key"
val signing_in = "Signing in"
val overview = "Tổng quan"
val all_devices = "Tất cả thiết bị"
val account_string = "Tài khoản"
val house_string = "Phòng"
val choose_house_to_control_string = "Chọn phòng để quản lý"
val sign_out_string = "Đăng xuất"
val group_string = "Group"
val ac_control_string = "Điều khiển điều hòa"
val light_control_string = "Điều khiển đèn"
val temperature_string = "Nhiệt độ"
val humid_string = "Độ ẩm"
val presence_device_string = "Cảm biến hiện diện"
val presence_detected = "Phát hiện hiện diện"
val presence_undetected = "Không phát hiện hiện diện"
val no_available_device_string = "Không có thiết bị"
val on_string = "Bật"
val off_string = "Tắt"